# Generated by Django 5.2 on 2025-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='posters')),
                ('name', models.CharField(max_length=50)),
                ('cast', models.TextField(max_length=50)),
                ('director', models.CharField(max_length=20)),
                ('synopsis', models.TextField(max_length=150)),
                ('Rating', models.FloatField(max_length=10)),
            ],
        ),
    ]
